name: Continuous-Deployment

# Trigger which git action (push, pull_request)
# in which branch(es) should start the jobs...
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# jobs to run
jobs:
  # build, the name of the job, a server to create and auto configure
  build:
    name: Publish the main branch to our web server
    runs-on: ubuntu-latest
    steps:
    - name: checkout the main branch
      uses: actions/checkout@v4  # anv채nder en f채rdig actions fr책n github
      with:
        ref: main

    - name: copy file via ssh password
      uses: appleboy/scp-action@v0.1.4
      with: # Alla secrets 채r tillagda i repots settings, Secrets and variables och Actions
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: '*.*' # kopierar allt i mappen och alla filer
        target: /var/www/auto-live